#!/bin/bash

echo "🎨 Render全栈部署指南"
echo "========================================"

echo ""
echo "📋 部署清单:"
echo "  ✅ 1. 后端API服务 (Web Service)"
echo "  ✅ 2. 前端门户网站 (Static Site)"  
echo "  ✅ 3. 管理后台系统 (Static Site)"
echo "  ✅ 4. 云数据库 (PlanetScale)"
echo ""

echo "🚀 部署步骤:"
echo ""
echo "【第1步】数据库设置 (5分钟)"
echo "  1. 访问 https://planetscale.com"
echo "  2. 创建数据库: xanadu-company"
echo "  3. 获取连接信息"
echo ""

echo "【第2步】后端API部署 (10分钟)"
echo "  1. 访问 https://dashboard.render.com"
echo "  2. New + → Web Service"
echo "  3. 连接GitHub: wangz1yu/XanaduCompany"
echo "  4. 配置:"
echo "     - Name: xanadu-backend"
echo "     - Environment: Node"
echo "     - Build Command: cd server && npm install"
echo "     - Start Command: cd server && npm start"
echo "  5. 环境变量:"
echo "     NODE_ENV=production"
echo "     PORT=10000"
echo "     DB_HOST=[PlanetScale主机]"
echo "     DB_PORT=3306"
echo "     DB_NAME=xanadu-company"
echo "     DB_USER=[PlanetScale用户名]"
echo "     DB_PASSWORD=[PlanetScale密码]"
echo ""

echo "【第3步】前端门户部署 (5分钟)"
echo "  1. New + → Static Site"
echo "  2. 连接同一个GitHub仓库"
echo "  3. 配置:"
echo "     - Name: xanadu-web"
echo "     - Build Command: cd web && npm install && npm run build"
echo "     - Publish Directory: web/dist"
echo ""

echo "【第4步】管理后台部署 (5分钟)"
echo "  1. New + → Static Site"
echo "  2. 连接同一个GitHub仓库"
echo "  3. 配置:"
echo "     - Name: xanadu-admin"
echo "     - Build Command: cd admin && npm install --legacy-peer-deps && NODE_OPTIONS=\"--openssl-legacy-provider\" npm run build:prod"
echo "     - Publish Directory: admin/dist"
echo ""

echo "【第5步】导入数据 (5分钟)"
echo "  1. 在PlanetScale Console中"
echo "  2. 执行 server/init/initial_data.sql"
echo ""

echo "🎯 预期结果:"
echo "  📱 前端门户: https://xanadu-web.onrender.com"
echo "  ⚙️  管理后台: https://xanadu-admin.onrender.com"  
echo "  🔌 API服务: https://xanadu-backend.onrender.com"
echo ""

echo "⏱️  总部署时间: 约30分钟"
echo "💰 总成本: 完全免费"
echo ""

echo "📖 详细指南参考:"
echo "  - render-fullstack-guide.md (完整架构说明)"
echo "  - planetscale-setup-guide.md (数据库设置)"
echo ""

echo "✨ 优势:"
echo "  🎯 统一平台管理"
echo "  🚀 更好的性能"
echo "  💰 成本控制"
echo "  🔧 简化配置"
echo ""

echo "🚀 准备就绪! 开始部署吧!"
